#!/usr/bin/env python3
# -*- coding: utf-8 -*-

def sum_negatives_between_min_max(a):
    if not a:
        return 0

    min_val = a[0]
    max_val = a[0]
    i_min = 0
    i_max = 0

    for i in range(1, len(a)):
        if a[i] < min_val:
            min_val = a[i]
            i_min = i
        if a[i] > max_val:
            max_val = a[i]
            i_max = i

    l, r = (i_min, i_max) if i_min < i_max else (i_max, i_min)

    s = 0
    for x in a[l + 1:r]:
        if x < 0:
            s += x
    return s


def main():
    n = int(input().strip())
    a = list(map(int, input().split()))
    if len(a) != n:
        while len(a) < n:
            a.extend(map(int, input().split()))
        a = a[:n]

    print(sum_negatives_between_min_max(a))


if __name__ == "__main__":
    main()
